#pragma once

typedef enum {
    SynthKey_C2,
    SynthKey_Db2,
    SynthKey_D2,
    SynthKey_Eb2,
    SynthKey_E2,
    SynthKey_F2,
    SynthKey_Gb2,
    SynthKey_G2,
    SynthKey_Ab2,
    SynthKey_A2,
    SynthKey_Bb2,
    SynthKey_B2,

    SynthKey_C3,
    SynthKey_Db3,
    SynthKey_D3,
    SynthKey_Eb3,
    SynthKey_E3,
    SynthKey_F3,
    SynthKey_Gb3,
    SynthKey_G3,
    SynthKey_Ab3,
    SynthKey_A3,
    SynthKey_Bb3,
    SynthKey_B3,

    SynthKey_C4,
    SynthKey_Db4,
    SynthKey_D4,
    SynthKey_Eb4,
    SynthKey_E4,
    SynthKey_F4,
    SynthKey_Gb4,
    SynthKey_G4,
    SynthKey_Ab4,
    SynthKey_A4,
    SynthKey_Bb4,
    SynthKey_B4,

    SynthKey_C5,
    SynthKey_Db5,
    SynthKey_D5,
    SynthKey_Eb5,
    SynthKey_E5,
    SynthKey_F5,
    SynthKey_Gb5,
    SynthKey_G5,
    SynthKey_Ab5,
    SynthKey_A5,
    SynthKey_Bb5,
    SynthKey_B5,

    SynthKey__Size,
} SynthKey;
