name: Build all
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  Ubuntu:
    if: github.event_name != 'schedule' || github.repository == 'juniorrantila/MusicStudio'
    runs-on: ubuntu-latest
    env:
      TEST_BUILD_ALL: 1
      TEST_FATAL_WARNINGS: ${{ github.event.inputs.fatal_warnings }}
    steps:
      - uses: actions/checkout@v3

      - name: Fetch tags and unshallow
        run: git fetch --unshallow --tags

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential freeglut3-dev libglew-dev libjack-jackd2-dev

      - name: Setup
        run: ./bootstrap

      - name: Build
        run: ninja -C build

  MacOS:
    if: github.event_name != 'schedule' || github.repository == 'juniorrantila/MusicStudio'
    runs-on: macos-latest
    env:
      TEST_BUILD_ALL: 1
      TEST_FATAL_WARNINGS: ${{ github.event.inputs.fatal_warnings }}
    steps:
      - uses: actions/checkout@v3

      - name: Fetch tags and unshallow
        run: git fetch --unshallow --tags

      - name: Setup
        run: ./bootstrap

      - name: Build
        run: ninja -C build
